### ISSUE TITLE
collapsing or expanding is not working. 

### ISSUE THREAD

**Issue by kikanijayesh** [baldogiRichard/apex-treegrid-enhancement-for-ig#3]
I am using the Tree Grid plugin in my application, and the application ID and parent values are quite long, around 12 to 15 digits. Could this cause any issues with collapsing or expanding nodes?

Example: 1234567890123456

**Comment by baldogiRichard** [comment]
Hi!

I've checked the treegrid by using large numbers as in your example. For me the treegrid works properly.

Does the plugin throws any errors on the web browsers console?

![image](https://github.com/user-attachments/assets/77885c10-aada-44ac-a756-e871ea0d237c)

Br,

Richard

**Comment by kikanijayesh** [comment]
Thanks for your response.

The tree grid is not throwing any exceptions, but it automatically expands one level and then freezes afterward.

**Comment by baldogiRichard** [comment]
Could you please show me an example on apex.oracle.com?

Richard

**Comment by baldogiRichard** [comment]
No further information was provided.
